# NumPy

NumPy is a Linear Algebra Library for Python.

Most of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

NumPy's arrays are more compact than Python lists -- a list of lists as you describe, in Python, would take at least 20 MB or so, while a NumPy 3D array with single-precision floats in the cells would fit in 4 MB. Access in reading and writing items is also faster with NumPy.

In [28]:
import numpy as np

## NumPy Arrays
NumPy arrays essentially comes in two floavors:
+ **Vectors** are strictly 1-d arrays.
+ **Matrices** are 2-d arrays.<br>
(Note: matrices can still have only one row or one column)

### Creating NumPy Arrays

<hr>

#### From a Python List
We can create an array by directly converting a python list or list of lists:

In [29]:
my_list = [1,2,3,4]
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [30]:
np.array(my_list)

array([1, 2, 3, 4])

In [31]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<hr>

#### Built-in methods
There are lots of built-in ways to generate Arrays

##### arange
It is similar to range() function of python and returns evenly spaces points within a given interval.

In [32]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

##### zeros and ones
Generate arrays of zeros and ones.

In [34]:
np.zeros(3)

array([0., 0., 0.])

In [35]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.ones(4)

array([1., 1., 1., 1.])

In [37]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### linspace
Return n number of points uniformly divided over a specified interval.

In [38]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

##### eye
Creates an identity matrix

In [40]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<hr>

#### insert

In [41]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a = np.insert(a, 3*2, [4,4])
a = np.reshape(a,(4,2))
a

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

<hr>

#### Random
Numpy also has a lots of ways to create random number arrays:

In [42]:
np.random.rand(5)

array([0.20199095, 0.6655469 , 0.24227012, 0.43135037, 0.122252  ])

In [43]:
np.random.rand(3,2)

array([[0.29496587, 0.13289554],
       [0.87070273, 0.4029704 ],
       [0.62641822, 0.6552579 ]])

##### randn
Return a sample from the "standard normal" distribution. Unlike rand which is uniform:

In [44]:
np.random.randn(4)

array([0.03048993, 0.2088796 , 0.58439702, 1.12346527])

In [45]:
np.random.randn(4,4)

array([[-0.29703969,  0.29711818, -0.30331348,  2.09618876],
       [ 2.62063125, -1.17292742,  0.40438365,  0.55255328],
       [ 1.40351141,  1.06941006, -1.66253407,  1.18572168],
       [ 0.17280136,  0.00293265, -1.09081881, -0.97196191]])

#### randint
Return random integers from low (inclusive) to high (exclusive).

In [46]:
np.random.randint(1,100)

51

In [47]:
rand_int_array = np.random.randint(1,100,20)
print(rand_int_array)

[20 61 75 82 70 25 59 89 71 97 74 96  4 98  5  5 26  6 13 18]


In [48]:
np.reshape(rand_int_array, (4, 5))

array([[20, 61, 75, 82, 70],
       [25, 59, 89, 71, 97],
       [74, 96,  4, 98,  5],
       [ 5, 26,  6, 13, 18]])

<hr>

#### Array Attributes and Methods

In [49]:
arr = np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [51]:
ranarr = np.random.randint(0, 50, 20)
print(ranarr)

[39  8  2 46 39 32  7 44 29 18  4 41 21 17  1 38 34  6 26 11]


##### Reshape
Returns an array containing the same data with a new shape.

In [54]:
ranarr = ranarr.reshape((4,5))
print(ranarr)

[[39  8  2 46 39]
 [32  7 44 29 18]
 [ 4 41 21 17  1]
 [38 34  6 26 11]]


##### max, min, argmax, argmin
These are used for finding max or min values. Or to find their index locations using argmin or argmax

In [55]:
print(ranarr)

[[39  8  2 46 39]
 [32  7 44 29 18]
 [ 4 41 21 17  1]
 [38 34  6 26 11]]


In [56]:
print(ranarr.max())
print(ranarr.min())

46
1


In [57]:
print(ranarr.argmax())
print(ranarr.argmin())

3
14


##### Shape
Shape is an attribute that arrays have (not a method):

In [60]:
print(arr.shape)
print(ranarr.shape)

(25,)
(4, 5)


In [61]:
arr.reshape(5,5).shape

(5, 5)

In [62]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

##### dtype
the data type of the object in the array.

In [64]:
print(arr.dtype)
print(ranarr.dtype)


int32
int32


<hr>