# NumPy Indexing and Selection

In [14]:
import numpy as np

In [54]:
# Creating a sample array
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<hr>

## Bracket Indexing and Selection
It is the simplest way to pick one or some elements of an array. It is very similar to python lists.

In [55]:
# Get a value at an index
arr[8]

8

In [59]:
# Get values in a range
print(arr[1:5])
print(arr[:3])
print(arr[6:])

[1 2 3 4]
[0 1 2]
[ 6  7  8  9 10]


<hr>

## Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast.

In [60]:
# setting a value to a range of indexes
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [61]:
# resetting the array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slices

In [62]:
# creating a slice of array
slice_of_arr = arr[2:6]
slice_of_arr

array([2, 3, 4, 5])

In [63]:
# now when we make changes in the slice, the changes in the slice
# the changes are also reflected in the original array.
slice_of_arr[:] = 99

print(slice_of_arr)
print(arr)

[99 99 99 99]
[ 0  1 99 99 99 99  6  7  8  9 10]


This is because data is not copied, it's a view of the original array! To save memory.

In [67]:
# To copy elements of an array o some other array, we need to
# to be explicit.

arr_copy = arr.copy()
arr_copy

array([ 0,  1, 99, 99, 99, 99,  6,  7,  8,  9, 10])

<hr>

## Indexing a 2D array (matrices)
The general format is **arr_2d[row][col]** or **arr_2d[row,col]**.

In [68]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
# indexing a row
arr_2d[1]

array([20, 25, 30])

In [71]:
# getting a individual element
print(arr_2d[1][0])
print(arr_2d[1,0])

20
20


### 2D array slicing 

In [75]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [76]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

### Fancy Indexing
Fancy indexing allows us to select entire rows or columns out of order.

In [77]:
# setup a matrix
arr2d = np.zeros((10,10))
for i in range(10):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following:

In [78]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [80]:
arr2d[[6,2,5,1]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [85]:
arr2d[[1,5,3],[2,6,4]]

array([1., 5., 3.])

<hr>

## Selection
Selection based off oncomparison operators.

In [88]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
# the following statement returns a array of boolean values.
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [91]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [92]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [93]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr[arr==5]

array([5])

<hr>